import logging
import pathlib

DEV = True
VER = "0.0.2"
STAGE = "alpha"

PORT = 33333
WS_PORT = 33334
WSS_PORT = 33335
SOCKET_BACKLOG_NUM = 5
MAX_RETRY_ATTEMPTS = 10
RETRY_ATTEMPTS_CLEAR_AFTER_SEC = 120
AUTOSAVE_INTERVAL_SEC = 300
ACC_CREATION_COOLDOWN_SEC = 30*60
NUM_ENCRYPT_ROUNDS = 15
LOG_LEVEL = logging.DEBUG if DEV else logging.INFO

ZSTD_COMPRESSION_LEVEL = 9 # -inf - 22
BROTLI_COMPRESSION_LEVEL = 11 # 0 - 11
GZIP_COMPRESSION_LEVEL = 3 # 0 - 9

TOKEN_EXPIRES_SEC = 60*60*24 # 1 Day
REDIRECT_TOKEN_EXPIRES_SEC = 60 # 1 Minute

CWD = pathlib.Path(__file__).resolve().parent
CA_CERT_DIR = CWD / "CA_CERT"
CDN_DIR = CWD / "cdn/"
CHATS_DIR = CWD / "Chats/"
SAVE_KEY = CWD / "meta.key"
CSS_DIR = CWD / "CSS/"
JS_DIR = CWD / "JS/"
LOG_DIR = CWD / "logs/"
MEDIA_DIR = CWD / "Media/"
PFP_DIR = CWD / "pfps/"
RUN_LOG_DIR = CWD / "runLogs/"
SECURITY_DIR = CWD / "security"
USERS_DIR = CWD / "Users/"

PRIVATE_DIRS = [
    USERS_DIR,
    CHATS_DIR,
    CA_CERT_DIR,
    SECURITY_DIR,
    SAVE_KEY,
    LOG_DIR,
    RUN_LOG_DIR
]

IMPORTANT_FILES = [
    CWD / "server.py",
    CWD / "httphelper.py"
]